CREATE DATABASE IF NOT EXISTS "Pessoa";
USE "Pessoa";

CREATE TABLE IF NOT EXISTS "Pessoa" (
	"ID" INT NOT NULL,
	"Nome" VARCHAR(100) NOT NULL COLLATE 'SQL_Latin1_General_CP1_CI_AS',
	"Idade" INT NOT NULL,
	"Telefone" VARCHAR(10) NOT NULL COLLATE 'SQL_Latin1_General_CP1_CI_AS',
	"Email" VARCHAR(30) NOT NULL COLLATE 'SQL_Latin1_General_CP1_CI_AS',
	PRIMARY KEY ("ID")
);
